name: Komunikacja Techniczna, zadanie domowe 
title: Bozena's reference file 
description: This is Bo≈ºena's example of technical documentation hosted on Github pages, using the Just the Docs Jekyll theme
remote_theme: boz-code/just-the-docs

color_scheme: dark

# logo: "/assets/images/Morris_badge.png"

aux_links:
  "Source repository on GitHub":
    - "//github.com/boz-code/boz-code.github.io"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "This documentation is part of the reference materials for the Technical Communication course at Vistula University (Warsaw). The content is based on <a href=\"https://github.com/flicstar/DITA-Mini-Manual\">Felicity Brand's example DITA project.</a>"